---
title: "Graph of Tennis Grand Slams"
author: "Rui Guo"
date: "2019/4/26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install library

```{r }
library(tidyverse)
library(lubridate)
```

## Load data

```{r}
gs <- read.csv("tidytuesday_2019_04_09/grand_slams.csv")
gs_time <- read.csv("tidytuesday_2019_04_09/grand_slam_timeline.csv")
players <- read.csv("tidytuesday_2019_04_09/player_dob.csv") 
```

## Question 1:

  Which tournaments is the bigest tournament by years?
  
#### Clean data first.
  
```{r}
gs_time_c <- gs_time %>% 
  na.omit() %>% 
  mutate(year = as.factor(year)) %>% 
  filter(outcome != "Absent")
```

  
#### Method 1
  

```{r}
tour_player <- gs_time_c %>% 
  group_by(tournament) %>% 
  summarize(num_play = n())

q1_plot_1 <- ggplot(tour_player, aes(x = tournament, y = num_play))+
  geom_bar(stat = "identity")

q1_plot_1
```


#### Method 2


```{r}
q1_plot_2 <- ggplot(gs_time_c, aes(x = tournament, fill = tournament))+
  geom_bar()

q1_plot_2

```


#### Extra practice: Which tournaments is the bigest tournament by decade？


```{r}
tour_player_year <- gs_time_c %>% 
  mutate(year = as.numeric(as.character(year)),
         decade = year - year%%10)
  
q1_ploy_3 <- ggplot(tour_player_year, aes(x = as.factor(decade),  xlab = "number", fill = tournament))+
  geom_bar( position = position_stack(reverse = T))+
  labs(x = "Decade", y = "Number of players") +
  coord_flip()
q1_ploy_3

```
  
## Question 2:

  Distribution of age by every 3 years. 
  
```{r}
player_age <- players %>% 
  na.omit() %>% 
  mutate(age_year = age%/%365,
         age_group = paste((age_year%/%3)*3, "-",(age_year%/%3)*3+2 ))
  
q2_ploy_1 <- ggplot(player_age, aes(x = as.factor(age_group), fill = age_group))+
  geom_bar()+
  labs(title = "Distribution of age by every 3 years",
      x="Age", 
      y = "Number of players",
      fill = "Age Group")

q2_ploy_1
```

#### Extra practice: The distribution of current age of the winners in last 5 years.

```{r}
age_gs_time <- left_join(gs_time, players, by = c("player" = "name")) %>% 
  mutate(real_age = floor(decimal_date(Sys.Date())-decimal_date(as.Date(date_of_birth))),
         age_group = paste((real_age%/%3)*3, "-",(real_age%/%3)*3+2)) %>% 
  filter(outcome =="Won",
         year > (max(year)-5)) %>% 
  group_by(age_group) %>% 
  summarise(counts= n())
  

q2_ploy_2 <- q2_ploy_1 <- ggplot(player_age, aes(x = as.factor(age_group), fill = age_group))+
  geom_bar()+
  labs(title = "Distribution of age by every 3 years & current age of the winners in last 5 years",
       x="Age", 
       y = "Number of players",
       fill = "Age group")+
  geom_point(data = age_gs_time, aes(x = age_group, y = counts, size = age_group, color = age_group))+ 
    labs(color = "Current age", size = "Current age")
q2_ploy_2

```

  
  
  
  
