---
title: "Tidy Tuesday 2019_04_16"
author: "Rui Guo"
date: "2019/4/29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load all data

```{r}
library(tidyverse)
brexit <- read_csv("data/tidytuesday_2019_04_16/brexit.csv")
corbyn <- read_csv("data/tidytuesday_2019_04_16/corbyn.csv")
dogs <- read_csv("data/tidytuesday_2019_04_16/dogs.csv")
eubalance <- read_csv("data/tidytuesday_2019_04_16/eu_balance.csv")
pensions <- read_csv("data/tidytuesday_2019_04_16/pensions.csv")
trade <- read_csv("data/tidytuesday_2019_04_16/trade.csv")
women_research <- read_csv("data/tidytuesday_2019_04_16/women_research.csv")
```

# Question 1: In data brexit.csv, guess how britain think about exit EU?

```{r}

brexit_long <- gather(brexit, key = "br_choose",value = "percent", -date, factor_key = TRUE)

q1_plot_1 <- ggplot(brexit_long, aes(x= as.Date(date, "%d/%m/%y"),y = percent, color= br_choose))+
  geom_line()+
  labs(title = "Should Britain exit from EU?", x= "Date", y = "Percent", color = "Responding")+
  scale_color_manual(labels=c("Right","Wrong"), values = c("green", "red"))+
  geom_smooth(method = lm, se = F,size = 4)+
  theme_bw()

q1_plot_1

```

# Question 2: In data brexit.csv, devide time to 4 stage, what is the choose in last day of each stage.

```{r}

rows <- nrow(brexit)

brexit_stage <- brexit[c(1, rows%/%3, rows%/%3*2, rows), ]

brexit_stage <- brexit_stage %>% 
  mutate(other = 100-percent_responding_right-percent_responding_wrong,
         date = as.factor(date))

brexit_stage_long <-gather(brexit_stage, key="type", value = "percent", -date) 

q2_plot_1 <- ggplot(brexit_stage_long, aes(x= "content",y = percent, fill = type))+
  geom_bar(stat = "identity", position = "stack", width = 1)+
  facet_grid(~as.factor(as.Date(date, "%d/%m/%y")))+
  coord_polar(theta = "y")

q2_plot_1


```

#### To make it looks better....

```{r}

q2_plot_2 <- ggplot(brexit_stage_long, aes(x = type, y = percent, fill = type)) +
  geom_bar(stat = "identity", alpha= 0.7)+
  coord_polar()+
  facet_grid(~as.factor(as.Date(date, "%d/%m/%y")))+
  labs(x = "", y = "")+ 
  theme(axis.text = element_blank(), 
        axis.ticks = element_blank(),
        legend.position = "none")

q2_plot_2  


q2_plot_3 <- ggplot(brexit_stage_long, aes(x = type, y = percent, fill = type)) +
  geom_bar(stat = "identity", alpha= 0.7)+
  coord_polar(theta = "y")+
  facet_grid(~as.factor(as.Date(date, "%d/%m/%y")))+
  labs(x = "", y = "")+ 
  theme(axis.text = element_blank(), 
        axis.ticks = element_blank(),
        legend.position = "none")

q2_plot_3 

```

# Question 3: in data corbyn.csv, which political or group is the popular on Facebook?
  <font color = blue> Want to draw a average value as a refrence line</font> 

```{r}
q3_plot_1 <- ggplot(corbyn, aes(x=political_group, y = avg_facebook_likes, fill = political_group))+
  geom_bar(stat = "identity")

q3_plot_1
```



